spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 7142220@qq.com #发送邮件的邮箱地址
    password:  atnrxkbmzzmnbijg #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 7142220@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

#自定义redis key
redis:
  key:
    prefix:
      authCode: protal:authCode
    expire:
      authCode: 300

